# Generated by Django 2.2.1 on 2020-03-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='joinMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koreanLastname', models.CharField(max_length=1)),
                ('koreanFirstname', models.CharField(max_length=3)),
                ('englishLastname', models.CharField(max_length=10)),
                ('englishFirstname', models.CharField(max_length=3)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('detailAddress', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('companyName', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=10)),
                ('fixedlineTelephone', models.CharField(max_length=20)),
            ],
        ),
    ]
