# Generated by Django 2.2.1 on 2020-03-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='joinMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koreanLastname', models.CharField(help_text='국문 이름을 입력해 주세요', max_length=1)),
                ('koreanFirstname', models.CharField(help_text='국문 성을 입력해 주세요', max_length=3)),
                ('englishLastname', models.CharField(help_text='영문 이름을 입력해 주세요', max_length=10)),
                ('englishFirstname', models.CharField(help_text='영문 성을 입력해 주세요', max_length=3)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(help_text='해당 이메일 주소로 이메일 티켓이 발송됩니다', max_length=50)),
                ('password', models.CharField(help_text='패스워드를 입력하여 주세요', max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('detailAddress', models.CharField(help_text='상세 주소를 입력해 주세요', max_length=50)),
                ('phoneNumber', models.CharField(help_text='핸드폰 번호를 입력해 주세요', max_length=20)),
                ('companyName', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=10)),
                ('fixedlineTelephone', models.CharField(help_text='유선전화번호를 입력해 주세요', max_length=20)),
            ],
        ),
    ]
