# Generated by Django 2.2.1 on 2020-03-21 06:04

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinmembership',
            name='fixedlineTelephone',
            field=phone_field.models.PhoneField(blank=True, help_text='전화번호를 입력해 주세요', max_length=31),
        ),
        migrations.AlterField(
            model_name='joinmembership',
            name='phoneNumber',
            field=phone_field.models.PhoneField(blank=True, help_text='핸드폰 번호를 입력해 주세요', max_length=31),
        ),
    ]
