# Generated by Django 2.2.1 on 2020-03-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20200321_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinmembership',
            name='detailAddress',
            field=models.CharField(help_text='상세 주소를 입력해 주세요', max_length=50),
        ),
        migrations.AlterField(
            model_name='joinmembership',
            name='email',
            field=models.EmailField(help_text='해당 이메일 주소로 이메일 티켓이 발송됩니다', max_length=50),
        ),
        migrations.AlterField(
            model_name='joinmembership',
            name='englishFirstname',
            field=models.CharField(help_text='영문 성을 입력해 주세요', max_length=3),
        ),
        migrations.AlterField(
            model_name='joinmembership',
            name='englishLastname',
            field=models.CharField(help_text='영문 이름을 입력해 주세요', max_length=10),
        ),
        migrations.AlterField(
            model_name='joinmembership',
            name='fixedlineTelephone',
            field=models.CharField(help_text='유선전화번호를 입력해 주세요', max_length=20),
        ),
        migrations.AlterField(
            model_name='joinmembership',
            name='koreanFirstname',
            field=models.CharField(help_text='국문 성을 입력해 주세요', max_length=3),
        ),
        migrations.AlterField(
            model_name='joinmembership',
            name='koreanLastname',
            field=models.CharField(help_text='국문 이름을 입력해 주세요', max_length=1),
        ),
        migrations.AlterField(
            model_name='joinmembership',
            name='phoneNumber',
            field=models.CharField(help_text='핸드폰 번호를 입력해 주세요', max_length=20),
        ),
    ]
