# Generated by Django 2.2.1 on 2020-04-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20200402_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='joinMembership',
            new_name='skyuser',
        ),
    ]
