# Generated by Django 2.2.1 on 2020-04-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20200402_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skyuser',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skyuser',
            name='companyName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skyuser',
            name='department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skyuser',
            name='detailAddress',
            field=models.CharField(help_text='상세 주소를 입력해 주세요', max_length=200),
        ),
        migrations.AlterField(
            model_name='skyuser',
            name='email',
            field=models.EmailField(help_text='해당 이메일 주소로 이메일 티켓이 발송됩니다', max_length=200),
        ),
        migrations.AlterField(
            model_name='skyuser',
            name='englishFirstname',
            field=models.CharField(help_text='영문 성을 입력해 주세요', max_length=200),
        ),
        migrations.AlterField(
            model_name='skyuser',
            name='englishLastname',
            field=models.CharField(help_text='영문 이름을 입력해 주세요', max_length=200),
        ),
        migrations.AlterField(
            model_name='skyuser',
            name='fixedlineTelephone',
            field=models.CharField(help_text='유선전화번호를 입력해 주세요', max_length=200),
        ),
        migrations.AlterField(
            model_name='skyuser',
            name='koreanFirstname',
            field=models.CharField(help_text='국문 성을 입력해 주세요', max_length=200),
        ),
        migrations.AlterField(
            model_name='skyuser',
            name='koreanLastname',
            field=models.CharField(help_text='국문 이름을 입력해 주세요', max_length=200),
        ),
        migrations.AlterField(
            model_name='skyuser',
            name='password',
            field=models.CharField(help_text='패스워드를 입력하여 주세요', max_length=200),
        ),
        migrations.AlterField(
            model_name='skyuser',
            name='phoneNumber',
            field=models.CharField(help_text='핸드폰 번호를 입력해 주세요', max_length=200),
        ),
        migrations.AlterField(
            model_name='skyuser',
            name='position',
            field=models.CharField(max_length=200),
        ),
    ]
