# Generated by Django 2.2.1 on 2020-04-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20200402_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kauser',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='kauser',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='kauser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='kauser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
