# Generated by Django 2.2.1 on 2020-04-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20200402_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kauser',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='kauser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='kauser',
            name='fixedlineTelephone',
        ),
        migrations.RemoveField(
            model_name='kauser',
            name='position',
        ),
    ]
