# Generated by Django 2.2.1 on 2020-04-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20200402_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kauser',
            name='birthday',
        ),
    ]
