# Generated by Django 2.2.1 on 2020-04-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0004_auto_20200402_2244'),
        ('authapp', '0008_remove_kauser_birthday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kauser',
            new_name='MyUser',
        ),
    ]
