# Generated by Django 2.2.1 on 2020-04-13 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SignupApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='myuser',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
