# Generated by Django 2.2.1 on 2020-04-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignupApp', '0003_auto_20200415_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(help_text='국문 성을 입력해 주세요', max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(help_text='국문 이름을 입력해 주세요', max_length=20),
        ),
    ]
