# Generated by Django 2.2.1 on 2020-03-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emailTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_of_payment', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ranking', models.CharField(max_length=200)),
                ('starting_point', models.CharField(max_length=200)),
                ('arrival', models.CharField(max_length=200)),
                ('flight_time', models.CharField(max_length=200)),
                ('seat_number', models.CharField(max_length=200)),
                ('aircraft_name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='flightAircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_name', models.CharField(max_length=200)),
                ('aircraft_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='flightNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='flightSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(max_length=200)),
                ('arrival', models.CharField(max_length=200)),
                ('flight_time', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_season_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('low_season_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='seatClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.CharField(max_length=200)),
            ],
        ),
    ]
