# Generated by Django 2.2.1 on 2020-05-23 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailticket',
            old_name='aircraft_name',
            new_name='comingDay',
        ),
        migrations.RenameField(
            model_name='emailticket',
            old_name='method_of_payment',
            new_name='daytogo',
        ),
        migrations.RemoveField(
            model_name='emailticket',
            name='number',
        ),
        migrations.RemoveField(
            model_name='emailticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='emailticket',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='emailticket',
            name='seat_number',
        ),
    ]
