# Generated by Django 2.2.1 on 2020-03-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='arrival',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='comingDay',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='daytogo',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='flight_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='starting_point',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
