# Generated by Django 2.2.1 on 2020-04-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightsection',
            name='price',
        ),
        migrations.RemoveField(
            model_name='flightsection',
            name='seatClass',
        ),
    ]
