# Generated by Django 2.2.1 on 2020-05-23 04:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0002_auto_20200523_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailticket',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 4, 25, 20, 981151, tzinfo=utc)),
        ),
    ]
