# Generated by Django 2.2.1 on 2020-03-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0002_auto_20200328_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='arrival',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='comingDay',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='daytogo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='flight_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='starting_point',
            field=models.CharField(max_length=5),
        ),
    ]
