# Generated by Django 2.2.1 on 2020-03-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0003_auto_20200330_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='comingDay',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='daytogo',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
