# Generated by Django 2.2.1 on 2020-05-23 04:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0004_auto_20200523_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailticket',
            name='comingDay',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emailticket',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 4, 51, 57, 880599, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emailticket',
            name='daytogo',
            field=models.DateField(),
        ),
    ]
