# Generated by Django 2.2.1 on 2020-05-23 05:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0005_auto_20200523_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailticket',
            name='arrival',
            field=models.CharField(choices=[('김포', '김포'), ('제주', '제주'), ('부산', '부산'), ('울산', '울산'), ('대구', '대구'), ('청주', '청주'), ('원주', '원주'), ('군산', '군산'), ('진주/사천', '진주/사천'), ('여수/순천', '여수/순천'), ('무안', '무안'), ('포항', '포항')], default='구간선택', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='emailticket',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 5, 13, 1, 410046, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emailticket',
            name='starting_point',
            field=models.CharField(choices=[('김포', '김포'), ('제주', '제주'), ('부산', '부산'), ('울산', '울산'), ('대구', '대구'), ('청주', '청주'), ('원주', '원주'), ('군산', '군산'), ('진주/사천', '진주/사천'), ('여수/순천', '여수/순천'), ('무안', '무안'), ('포항', '포항')], default='구간선택', max_length=5, null=True),
        ),
    ]
