# Generated by Django 2.2.1 on 2020-03-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0005_auto_20200331_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='comingDay',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='daytogo',
            field=models.DateField(),
        ),
    ]
