# Generated by Django 2.2.1 on 2020-03-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0006_auto_20200318_1209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email_ticket',
            new_name='emailTicket',
        ),
        migrations.RenameModel(
            old_name='Flight_aircraft',
            new_name='flightAircraft',
        ),
        migrations.RenameModel(
            old_name='Seat_class',
            new_name='flightNumber',
        ),
        migrations.RenameModel(
            old_name='Flight_section',
            new_name='flightSection',
        ),
        migrations.RenameModel(
            old_name='Flight_number',
            new_name='seatClass',
        ),
        migrations.RenameField(
            model_name='flightnumber',
            old_name='ranking',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='seatclass',
            old_name='number',
            new_name='ranking',
        ),
    ]
