# Generated by Django 2.2.1 on 2020-05-23 05:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0006_auto_20200523_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 5, 26, 15, 293227, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emailticket',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 5, 26, 15, 294037, tzinfo=utc)),
        ),
    ]
