# Generated by Django 2.2.1 on 2020-04-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0007_auto_20200407_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='seatClass',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ReservationApp.seatClass'),
        ),
    ]
