# Generated by Django 2.2.1 on 2020-04-07 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0010_auto_20200407_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='arrival',
            field=models.CharField(choices=[('김포', '김포'), ('제주', '제주'), ('부산', '부산'), ('울산', '울산'), ('대구', '대구'), ('청주', '청주'), ('원주', '원주'), ('군산', '군산'), ('진주/사천', '진주/사천'), ('여수/순천', '여수/순천'), ('무안', '무안'), ('포항', '포항')], default='구간선택', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='price',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ReservationApp.price'),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='seatClass',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ReservationApp.seatClass'),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='starting_point',
            field=models.CharField(choices=[('김포', '김포'), ('제주', '제주'), ('부산', '부산'), ('울산', '울산'), ('대구', '대구'), ('청주', '청주'), ('원주', '원주'), ('군산', '군산'), ('진주/사천', '진주/사천'), ('여수/순천', '여수/순천'), ('무안', '무안'), ('포항', '포항')], default='구간선택', max_length=5, null=True),
        ),
    ]
