# Generated by Django 2.2.1 on 2020-04-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0011_auto_20200407_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='price',
            field=models.ForeignKey(default='가격', null=True, on_delete=django.db.models.deletion.CASCADE, to='ReservationApp.price'),
        ),
        migrations.AlterField(
            model_name='flightsection',
            name='seatClass',
            field=models.ForeignKey(default='좌석등급', null=True, on_delete=django.db.models.deletion.CASCADE, to='ReservationApp.seatClass'),
        ),
    ]
