# Generated by Django 2.2.1 on 2020-04-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0012_auto_20200407_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightsection',
            name='price',
        ),
        migrations.RemoveField(
            model_name='flightsection',
            name='seatClass',
        ),
    ]
