# Generated by Django 2.2.1 on 2020-04-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0014_auto_20200407_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightsection',
            name='price',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ReservationApp.price'),
        ),
    ]
