# Generated by Django 2.2.1 on 2020-04-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0016_auto_20200407_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightsection',
            name='price',
        ),
        migrations.RemoveField(
            model_name='flightsection',
            name='seatClass',
        ),
    ]
